name: hmtnote_annotate
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::hmtnote=0.7.2
  - conda-forge::python=3.10.11 # Locked with the container
  - conda-forge::pip
  - pip:
      - aiohttp=3.7.4.post0 # Locked with the container
