---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::kat=2.4.2
  - conda-forge::python=3.8.5 # Locked with the container
  - conda-forge::numpy=1.19.1 # Locked with the container
  - conda-forge::scipy=1.5.2 # Locked with the container
  - conda-forge::matplotlib=3.3.1 # Locked with the container
